# Generated by Django 6.0.7 on 2026-07-12 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاختبار')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاختبار')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة الاختبار (بالدقائق)')),
                ('start_time', models.DateTimeField(verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور للطلاب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'جاري الحل'), ('submitted', 'بانتظار التصحيح'), ('graded', 'تم التصحيح')], default='in_progress', max_length=15)),
                ('auto_score', models.FloatField(default=0)),
                ('essay_score', models.FloatField(default=0)),
                ('is_released', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
            ],
            options={
                'verbose_name': 'محاولة',
                'verbose_name_plural': 'المحاولات',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('essay', 'سؤال مقالي')], default='mcq', max_length=10, verbose_name='نوع السؤال')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('marks', models.PositiveIntegerField(default=1, verbose_name='الدرجة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'الخيارات',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_text', models.TextField(blank=True, verbose_name='إجابة الطالب')),
                ('awarded_marks', models.FloatField(blank=True, null=True, verbose_name='الدرجة الممنوحة')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
